In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
current_folder = os.getcwd()
file_path = os.path.join(current_folder,'..' ,'resource', 'RSMC_Best_Track_Data.csv')
df = pd.read_csv(file_path)
df.head()

,International number ID,Name of the storm,Time of analysis,Grade,Latitude of the center,Longitude of the center,Central pressure,Maximum sustained wind speed,Direction of the longest radius of 50kt winds or greater,The longest radius of 50kt winds or greater,The shortest radius of 50kt winds or greater,Direction of the longest radius of 30kt winds or greater,The longest radius of 30kt winds or greater,The shortest radius of 30kt winds or greater,Indicator of landfall or passage
0,5101,NaN,1951-02-19 06:00:00,Tropical Depression (TD),20.0,138.5,1010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
1,5101,NaN,1951-02-19 12:00:00,Tropical Depression (TD),20.0,138.5,1010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
2,5101,NaN,1951-02-19 18:00:00,Tropical Depression (TD),23.0,142.1,1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
3,5101,NaN,1951-02-20 00:00:00,Tropical Cyclone of TS intensity or higher,25.0,146.0,994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
4,5101,NaN,1951-02-20 06:00:00,Tropical Cyclone of TS intensity or higher,27.6,150.6,994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,

In [3]:
df['Time of analysis'] = pd.to_datetime(df['Time of analysis'])

# 创建新列
df['year'] = df['Time of analysis'].dt.year
df['month'] = df['Time of analysis'].dt.month
df['day'] = df['Time of analysis'].dt.day
df['hour'] = df['Time of analysis'].dt.hour

df.head()

,International number ID,Name of the storm,Time of analysis,Grade,Latitude of the center,Longitude of the center,Central pressure,Maximum sustained wind speed,Direction of the longest radius of 50kt winds or greater,The longest radius of 50kt winds or greater,The shortest radius of 50kt winds or greater,Direction of the longest radius of 30kt winds or greater,The longest radius of 30kt winds or greater,The shortest radius of 30kt winds or greater,Indicator of landfall or passage,year,month,day,hour
0,5101,NaN,1951-02-19 06:00:00,Tropical Depression (TD),20.0,138.5,1010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1951,2,19,6
1,5101,NaN,1951-02-19 12:00:00,Tropical Depression (TD),20.0,138.5,1010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1951,2,19,12
2,5101,NaN,1951-02-19 18:00:00,Tropical Depression (TD),23.0,142.1,1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1951,2,19,18
3,5101,NaN,1951-02-20 00:00:00,Tropical Cyclone of TS intensity or higher,25.0,146.0,994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1951,2,20,0
4,5101,NaN,1951-02-20 06:00:00,Tropical Cyclone of TS intensity or higher,27.6,150.6,994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1951,2,20,6

In [4]:
df1 = df[df["year"] == 1951]
df2 = df1["International number ID"]
df2

0      5101
1      5101
2      5101
3      5101
4      5101
       ...
787    5121
788    5121
789    5121
790    5121
791    5121
Name: International number ID, Length: 792, dtype: int64

In [5]:
df['International number ID'] = df['International number ID'].astype(str)
df['International number ID'] = df['International number ID'].apply(lambda x: x.zfill(4))
df['International number ID'].sample(10)

68508    2220
17195    6814
19295    7024
48868    0023
8464     6103
49506    0118
22724    7406
5938     5814
68297    2212
43533    9432
Name: International number ID, dtype: object

In [7]:
id_no = "0608"
lat = df.loc[df['International number ID'] == id_no, 'Latitude of the center'] 
longi = df.loc[df['International number ID'] == id_no, 'Longitude of the center']
coor = pd.concat([lat, longi], axis=1)
arr = coor.values
coor.values.tolist()

[[10.0, 148.5],
 [10.9, 147.4],
 [11.7, 146.5],
 [12.8, 145.5],
 [14.0, 144.2],
 [15.2, 143.1],
 [16.4, 141.6],
 [17.1, 140.5],
 [17.9, 139.5],
 [18.8, 138.2],
 [19.5, 136.7],
 [20.3, 135.4],
 [20.9, 134.0],
 [21.6, 132.9],
 [22.4, 131.4],
 [22.7, 130.8],
 [23.1, 130.1],
 [23.6, 129.3],
 [23.9, 128.4],
 [24.3, 127.6],
 [24.7, 126.9],
 [25.1, 126.1],
 [25.4, 125.3],
 [25.7, 124.4],
 [26.0, 123.7],
 [26.3, 123.0],
 [26.5, 122.5],
 [27.0, 121.2],
 [27.2, 120.0],
 [27.4, 118.7],
 [28.2, 117.3],
 [28.6, 116.1],
 [29.5, 114.7],
 [30.0, 113.1]]